const { test, expect } = require('@jest/globals');
const topTenEconomicalBowlers = require('../src/server/4-top-10-economical-bowlers-in-2015');

const matches = [
  {
    id: '1',
    season: '2015',
    team1: 'Sunrisers Hyderabad',
    team2: 'Royal Challengers Bangalore',
    toss_winner: 'Royal Challengers Bangalore',
    winner: 'Sunrisers Hyderabad',
  },
  {
    id: '2',
    season: '2015',
    team1: 'Chennai Super Kings',
    team2: 'Delhi Daredevils',
    toss_winner: 'Chennai Super Kings',
    winner: 'Chennai Super Kings',
  },
  {
    id: '3',
    season: '2016',
    date: '2017-04-05',
    team1: 'Kings Xi Punjab',
    team2: 'Mumbai Indians',
    toss_winner: 'Kings Xi Punjab',
    winner: 'Mumbai Indians',
  },
];

const deliveries = [
  {
    match_id: '1',
    bowler: 'TS Mills',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '1',
  },

  {
    match_id: '1',
    bowler: 'TS Mills',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '1',
  },
  {
    match_id: '1',
    bowler: 'TS Mills',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '1',
  },
  {
    match_id: '1',
    bowler: 'TS Mills',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '1',
  },
  {
    match_id: '1',
    bowler: 'TS Mills',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '1',
  },
  {
    match_id: '1',
    bowler: 'TS Mills',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '1',
  },
  {
    match_id: '1',
    bowler: 'J Bumrah',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '4',
  },
  {
    match_id: '1',
    bowler: 'J Bumrah',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '4',
  },
  {
    match_id: '1',
    bowler: 'J Bumrah',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '4',
  },
  {
    match_id: '1',
    bowler: 'J Bumrah',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '4',
  },
  {
    match_id: '1',
    bowler: 'J Bumrah',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '4',
  },
  {
    match_id: '1',
    bowler: 'J Bumrah',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '4',
  },
  {
    match_id: '2',
    bowler: 'J Archer',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '2',
  },
  {
    match_id: '2',
    bowler: 'J Archer',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '2',
  },
  {
    match_id: '2',
    bowler: 'J Archer',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '2',
  },
  {
    match_id: '2',
    bowler: 'J Archer',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '2',
  },
  {
    match_id: '2',
    bowler: 'J Archer',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '2',
  },
  {
    match_id: '2',
    bowler: 'J Archer',
    wide_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '2',
  },
];

test('Calcultem top 10 economical bowlers in 2015', () => {
  expect(topTenEconomicalBowlers(matches, deliveries)).toMatchObject({
    'TS Mills': 6,
    'J Archer': 12,
    'J Bumrah': 24,
  });
});
